import {
  ZC_ETH_ETH_ADDRESS,
  ZC_USDC_ETH_ADDRESS,
  ZC_USDT_ETH_ADDRESS,
  ZC_DAI_ETH_ADDRESS,
  ZC_ETH_BASE_ADDRESS,
  ZC_USDC_BASE_ADDRESS,
  ZC_POL_POL_ADDRESS,
  ZC_USDT_POL_ADDRESS,
  ZC_USDC_POL_ADDRESS,
  ZC_SOL_SOL_ADDRESS,
  ZC_USDC_SOL_ADDRESS,
  ZC_USDT_SOL_ADDRESS,
  ZC_USDC_BSC_ADDRESS,
  ZC_BNB_BSC_ADDRESS,
  ZC_USDT_BSC_ADDRESS,
  ZC_BTC_BTC_ADDRESS,
  ZC_USDC_ARB_ADDRESS,
  ZC_USDT_ARB_ADDRESS,
  ZC_ETH_ARB_ADDRESS,
  ZC_USDT_AVAX_ADDRESS,
  ZC_AVAX_AVAX_ADDRESS,
  ZC_USDC_AVAX_ADDRESS,
} from "../../../constants";
import { Token } from "../types/types";
import { EMPTY_BALANCE } from "@/utils/helpers";


export const ZRC20_TOKENS_BY_ADDRESS: { [address: string]: Token } = {
  [ZC_ETH_ETH_ADDRESS]: {
    symbol: "ETH.ETH",
    address: ZC_ETH_ETH_ADDRESS,
    decimals: 18,
    imgURL: "/ETH.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDC_ETH_ADDRESS]: {
    symbol: "USDC.ETH",
    address: ZC_USDC_ETH_ADDRESS,
    decimals: 6,
    imgURL: "/USDC.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDT_ETH_ADDRESS]: {
    symbol: "USDT.ETH",
    address: ZC_USDT_ETH_ADDRESS,
    decimals: 6,
    imgURL: "/usdt.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_DAI_ETH_ADDRESS]: {
    symbol: "DAI.ETH",
    address: ZC_DAI_ETH_ADDRESS,
    decimals: 18,
    imgURL: "/dai.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_ETH_BASE_ADDRESS]: {
    symbol: "ETH.BASE",
    address: ZC_ETH_BASE_ADDRESS,
    decimals: 18,
    imgURL: "/ETH.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDC_BASE_ADDRESS]: {
    symbol: "USDC.BASE",
    address: ZC_USDC_BASE_ADDRESS,
    decimals: 6,
    imgURL: "/USDC.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_POL_POL_ADDRESS]: {
    symbol: "POL.POL",
    address: ZC_POL_POL_ADDRESS,
    decimals: 18,
    imgURL: "/polygon_logo.png",
    price: 0.7159,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDT_POL_ADDRESS]: {
    symbol: "USDT.POL",
    address: ZC_USDT_POL_ADDRESS,
    decimals: 6,
    imgURL: "/usdt.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDC_POL_ADDRESS]: {
    symbol: "USDC.POL",
    address: ZC_USDC_POL_ADDRESS,
    decimals: 6,
    imgURL: "/USDC.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_SOL_SOL_ADDRESS]: {
    symbol: "SOL.SOL",
    address: ZC_SOL_SOL_ADDRESS,
    decimals: 9,
    imgURL: "/solana_logo.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDC_SOL_ADDRESS]: {
    symbol: "USDC.SOL",
    address: ZC_USDC_SOL_ADDRESS,
    decimals: 6,
    imgURL: "/USDC.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDT_SOL_ADDRESS]: {
    symbol: "USDT.SOL",
    address: ZC_USDT_SOL_ADDRESS,
    decimals: 6,
    imgURL: "/USDT.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDC_BSC_ADDRESS]: {
    symbol: "USDC.BSC",
    address: ZC_USDC_BSC_ADDRESS,
    decimals: 18,
    imgURL: "/USDC.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_BNB_BSC_ADDRESS]: {
    symbol: "BNB.BSC",
    address: ZC_BNB_BSC_ADDRESS,
    decimals: 18,
    imgURL: "/bnb_logo.png",
    price: 734,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDT_BSC_ADDRESS]: {
    symbol: "USDT.BSC",
    address: ZC_USDT_BSC_ADDRESS,
    decimals: 18,
    imgURL: "/usdt.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_BTC_BTC_ADDRESS]: {
    symbol: "BTC.BTC",
    address: ZC_BTC_BTC_ADDRESS,
    decimals: 8,
    imgURL: "/btc.png",
    price: 97303,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDC_ARB_ADDRESS]: {
    symbol: "USDC.ARB",
    address: ZC_USDC_ARB_ADDRESS,
    decimals: 6,
    imgURL: "/USDC.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDT_ARB_ADDRESS]: {
    symbol: "USDT.ARB",
    address: ZC_USDT_ARB_ADDRESS,
    decimals: 6,
    imgURL: "/usdt.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_ETH_ARB_ADDRESS]: {
    symbol: "ETH.ARB",
    address: ZC_ETH_ARB_ADDRESS,
    decimals: 18,
    imgURL: "/ETH.png",
    price: 3904, // or your current ETH price
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDT_AVAX_ADDRESS]: {
    symbol: "USDT.AVAX",
    address: ZC_USDT_AVAX_ADDRESS,
    decimals: 6,
    imgURL: "/usdt.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_AVAX_AVAX_ADDRESS]: {
    symbol: "AVAX.AVAX",
    address: ZC_AVAX_AVAX_ADDRESS,
    decimals: 18,
    imgURL: "/avalanche-avax-logo.png",
    price: 35, // approximate AVAX price (or update dynamically)
    balance: EMPTY_BALANCE,
    isNative: false,
  },
  [ZC_USDC_AVAX_ADDRESS]: {
    symbol: "USDC.AVAX",
    address: ZC_USDC_AVAX_ADDRESS,
    decimals: 6,
    imgURL: "/USDC.png",
    price: 1,
    balance: EMPTY_BALANCE,
    isNative: false,
  },
};
